//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tracker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tracker2Entities : DbContext
    {
        public tracker2Entities()
            : base("name=tracker2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<affiliate> affiliate { get; set; }
        public virtual DbSet<AffiliateParameter> AffiliateParameter { get; set; }
        public virtual DbSet<AffiliateSource> AffiliateSource { get; set; }
        public virtual DbSet<AppEvent> AppEvent { get; set; }
        public virtual DbSet<appName> appName { get; set; }
        public virtual DbSet<campaign> campaign { get; set; }
        public virtual DbSet<campaign_offer> campaign_offer { get; set; }
        public virtual DbSet<CampaignLog> CampaignLog { get; set; }
        public virtual DbSet<campaignPath> campaignPath { get; set; }
        public virtual DbSet<click> click { get; set; }
        public virtual DbSet<clickCount> clickCount { get; set; }
        public virtual DbSet<clickIdByname> clickIdByname { get; set; }
        public virtual DbSet<country> country { get; set; }
        public virtual DbSet<domain> domain { get; set; }
        public virtual DbSet<ifa> ifa { get; set; }
        public virtual DbSet<ip> ip { get; set; }
        public virtual DbSet<ipDB> ipDB { get; set; }
        public virtual DbSet<languageDB> languageDB { get; set; }
        public virtual DbSet<loginHistory> loginHistory { get; set; }
        public virtual DbSet<LWCallback> LWCallback { get; set; }
        public virtual DbSet<MediaBuy_Campaign> MediaBuy_Campaign { get; set; }
        public virtual DbSet<MediaBuyLink> MediaBuyLink { get; set; }
        public virtual DbSet<offer> offer { get; set; }
        public virtual DbSet<offerDayStatistics> offerDayStatistics { get; set; }
        public virtual DbSet<offerReportList> offerReportList { get; set; }
        public virtual DbSet<offerSource> offerSource { get; set; }
        public virtual DbSet<postbackPath> postbackPath { get; set; }
        public virtual DbSet<siteDomain> siteDomain { get; set; }
        public virtual DbSet<siteId> siteId { get; set; }
        public virtual DbSet<source> source { get; set; }
        public virtual DbSet<Sources> Sources { get; set; }
        public virtual DbSet<SourcesItem> SourcesItem { get; set; }
        public virtual DbSet<trafficSource> trafficSource { get; set; }
        public virtual DbSet<uaDB> uaDB { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
